import turtle 
import random 
w = turtle.Screen()
t = turtle.Turtle()
w.setup(width=1000, height=800)
w.bgcolor("skyblue")
w.title("Turtle Project")
x_coords = [ 80, 150, ]
y_coords = [-80, -250]
for _ in range(5):
    # Select random values independently
    random_x = random.choice(x_coords)
    random_y = random.choice(y_coords)

for i in range(1):
        t.speed(0)
        t.penup()
        t.goto(-500,-252)
        t.pendown()
        t.begin_fill()
        t.color("white", "white")
        t.forward(1010)
        t.rt(90)
        t.forward(50)
        t.rt(90)
        t.forward(1010)
        t.rt(90)
        t.forward(50)
        t.end_fill()
#end of the rail
        t.penup()
        t.goto(random_x,-252)
        t.pendown()    
        t.begin_fill()
        t.color("white", "white")
        t.forward(40)
        t.right(45)
        t.forward(40)
        t.right(90)
        t.forward(40)
        t.right(45)
        t.forward(180)
        t.right(90)
        t.forward(57)
        t.right(90)
        t.forward(180)
        t.end_fill()
#post 2
        t.penup()
        t.goto(300,-252)
        t.pendown()    
        t.begin_fill()
        t.color("white", "white")
        t.forward(40)
        t.right(45)
        t.forward(40)
        t.right(90)
        t.forward(40)
        t.right(45)
        t.forward(180)
        t.right(90)
        t.forward(57)
        t.right(90)
        t.forward(180)
        t.end_fill()
#post 3
        t.penup()
        t.goto(-300,-252)
        t.pendown()    
        t.begin_fill()
        t.color("white", "white")
        t.forward(40)
        t.right(45)
        t.forward(40)
        t.right(90)
        t.forward(40)
        t.right(45)
        t.forward(180)
        t.right(90)
        t.forward(57)
        t.right(90)
        t.forward(180)
        t.end_fill()
#post 4
        t.penup()
        t.goto(y_coords[0], -252)
        t.pendown()    
        t.begin_fill()
        t.color("white", "white")
        t.forward(40)
        t.right(45)
        t.forward(40)
        t.right(90)
        t.forward(40)
        t.right(45)
        t.forward(180)
        t.right(90)
        t.forward(57)
        t.right(90)
        t.forward(180)
        t.end_fill()
#post 5
        t.penup()
        t.goto(-450,-252)
        t.pendown()    
        t.begin_fill()
        t.color("white", "white")
        t.forward(40)
        t.right(45)
        t.forward(40)
        t.right(90)
        t.forward(40)
        t.right(45)
        t.forward(180)
        t.right(90)
        t.forward(57)
        t.right(90)
        t.forward(180)
        t.end_fill()
#post 6
        t.penup()
        t.goto(430,-252)
        t.pendown()    
        t.begin_fill()
        t.color("white", "white")
        t.forward(40)
        t.right(45)
        t.forward(40)
        t.right(90)
        t.forward(40)
        t.right(45)
        t.forward(180)
        t.right(90)
        t.forward(57)
        t.right(90)
        t.forward(180)
        t.end_fill()
        sun = turtle.Turtle()
#end of frense
sun.color("red", "yellow")
sun.speed(10)
sun.begin_fill()
for i in range(10):
    sun.forward(200)
    sun.left(280)
sun.end_fill()
        
w.exitonclick()
       

